### PR TITLE
Increase fps for most scenes to 40

### PR DESCRIPTION
**Pull request by Doctoror**
Increase FPS to 40 for all scenes except:
- eyes
- firework

FPS is increased by generating new matrixTransform and colorTransform frames by linear averaging between
existing frames. Example:

Let's say we had animation that starts with following matrixTransform frames:
```
[0f, 1f, 2f, 3f],
[2f, 3f, 4f, 5f]
[     ...      ]
[..last frame..]
```

Then, one more frame between each matrixTransform frames pairs is inserted:
```
[0f, 1f, 2f, 3f],
[1f, 2f, 3f, 4f],
[2f, 3f, 4f, 5f]
[     ...      ]
[..last frame..]
```

This way, we get `2x - 1` `matrixTransforms` and `colorTransforms`, which means that we can increase from
20 fps to 40 without increasing speed.

Now, every scene will have its own FPS setting.
Previously mentioned scenes will remain at `20`.

For scenes that have textures, no new textures were generated, instead, `animCounterSkip` is used to skip `animCounter` increment every second frame. Looks good.

You can switch and review individual commits if you find this easier to review like this.
Some scene transforms were to large to compile, they were moved to `assets`.
File structure is explained in array reader class javadoc.

### CODE REVIEW

**Comment by SCratORS** [comment]
it probably makes sense to transfer all transformation matrices to assets. But I do not know how to do it :-)

**Comment by Doctoror** [comment]
I was thinking about that too. Not sure if it has any benefits. The apk size would probably be the same and the arrays will not be readable unless you read that binary file and println the contents.

I did not commit the script I used to generate the binaries but I can do it.
I run it as a unit test but I am not sure how to add unit tests for your project.

This project has unconventional paths for source sets.
Usually main source sets are in
```
[moduleName]/src/main/java
[moduleName]/src/main/res
```

and tests go to
```
[moduleName]/src/test/java
```

I don't know how your source sets are configured because you commited root folder inside root_dir  instead of moving this dir under root project directory.

I can open a PR with conventional setup if you like.
This means all sources will be moved to new location, and it will be harder to look for git history of individual files from IDE.

**Comment by SCratORS** [comment]
I am not sure that I can correctly redo the directory structure in a git project.

**Comment by SCratORS** [comment]
perhaps it makes sense for me to give you access to the repository?

**Comment by Doctoror** [comment]
You don't need to give me access for this. I can open a pull request with new directory structure.

**Comment by SCratORS** [comment]
Yes, of course

**Pull request merged**
