### PR TITLE
Use wider grass images for landscape or wide screens

### PR DESCRIPTION
**Pull request by Doctoror**
Also, merge images for easier usage in different scales.

Pixel 7 Pro

Foldable

### CODE REVIEW

**Comment by SCratORS** [comment]
I am against combining the component parts of a bitmap image into a single file.
I deliberately left them consisting of parts, as in the original.
This is necessary so that everything can be replaced with the original files without changing the code.

**Comment by Doctoror** [comment]
Why is it needed to keep the ability to replace with originals?
I can also keep the originals but then it would be required to edit offset values as scale changes and it makes code complicated.

**Comment by SCratORS** [comment]
I just want to keep the compatibility as a tribute to the original.

**Comment by Doctoror** [comment]
I will open a new PR after I adjust the split images.

**Pull request closed without merging**
