### PR TITLE
[Calendar update fixed] Reuse and dependency-inject Calendar

### LINKED ISSUE #3: Expensive operation Calendar.getInstance is called on every frame
Calendar should be cached as a field instead of method variable, see:
https://github.com/SCratORS/Everchanging/blob/main/java/com/scrat/everchanging/EverchangingRender.java#L188
https://github.com/SCratORS/Everchanging/blob/main/java/com/scrat/everchanging/BackgroundScene.java#L22
https://github.com/SCratORS/Everchanging/blob/main/java/com/scrat/everchanging/FireWork.java#L38
https://github.com/SCratORS/Everchanging/blob/main/java/com/scrat/everchanging/ButterFlie.java#L1030
https://github.com/SCratORS/Everchanging/blob/main/java/com/scrat/everchanging/Dandelion.java#L270
...
the list is not exhaustive.

### PR DESCRIPTION
**Pull request by Doctoror**
This fixes #3

This is an amended commit that fixes time update issue.
Calendar will recompute time around every 40 seconds (every 800 frames assuming 20 fps).
Why 40 and not 60 seconds were chosen is to reduce possibility of being late by one minute for events like New Year.

### CODE REVIEW

**Comment by SCratORS** [comment]
Does it even make sense to cache the calendar? Using it with every "update" does not entail any load.
I won't merge yet. I will leave this "pull request" open for the future.

**Comment by Doctoror** [comment]
New calendar instance was created for every frame, which is quite expensive, see
https://stackoverflow.com/questions/28704832/calendar-instances-are-particularly-expensive-to-create

**Comment by SCratORS** [comment]
Convinced

**Comment by SCratORS** [comment]
if the phone is with the screen off, then all application activity stops. this means that the counter also stops working. when the background or animation changes when the screen is turned off, then after turning on the screen, those animations and backgrounds that were before the screen was turned off are played, in order for them to update, you must look at the screen for 800 "refresh" cycles, that is, 40 seconds, after which everything will change. But the user will not look to wait for the animation to change, he will say after 5 seconds that there is no animation change and will give a bad rating.

**Comment by Doctoror** [comment]
Yes, good point, I haven't noticed your comment earlier. Noticed it just now.

**Pull request merged**
